### ISSUE TITLE
Why not using the interface keyword

### ISSUE THREAD

**Issue by iddan** [michaelficarra/proposal-first-class-protocols#28] opened 2017-10-24 22:43 UTC
- It's used by Java & C#
 - It's used by Typescript Flowtype

**Comment by ljharb** [comment] 2017-10-24 22:56
I believe Typescript's use of it is the primary reason this proposal isn't using it; see #3.

**Comment by michaelficarra** [comment] 2017-10-24 23:01
> It's used by Typescript Flowtype

And it's exactly your association with that that makes the name infeasible. It's not the same feature. Closing as duplicate of #3.

**Closed by michaelficarra** 2017-10-24 23:01 UTC
